# Site settings
# Name of your site (displayed in the header)
name: Judo Club Broye

# Short bio or description (displayed in the header)
description: Vaud et Fribourg en kimono

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/10406113

title: Judo Club Broye 
email: your-email@domain.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
