- name: Technique 1
  jour: mardi
  heure: 18:15 - 19:15
  description: Pour les enfants dès 5 ans.
  image: images/slider-1.jpg

- name: Technique 2
  jour: mardi
  heure: 19:15 - 20:15
  description: Pour les enfants dès 8 ans.
  image: images/slider-1.jpg
  
- name: Technique 3
  jour: mercredi
  heure: 19:00 - 20:30
  description: Pour les enfants dès 13 ans.
  image: images/slider-1.jpg

- name: Technique 4
  jour: vendredi
  heure: 19:00 - 20:30
  description: Pour les enfants dès 13 ans.
  image: images/slider-3.jpg
